name: chekout-GHA
on: push
jobs:
  chekout-GHA-jobid:
    name: chekout-GHA-job
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v4
      - name: verifying the code
        run: |
          cat index.html
          ls -lahrt
          git branch
