name: push-job-wf
on:
  push:
    branches:
      - main
      - dev
jobs:
  push-branch-jobd:
    name: push-branch-job
    runs-on: ubuntu-latest
    steps:
      - name: push-step-all-branches
        run: echo "this is push from main and dev branch"