name: hello-world-wf
on: workflow_dispatch
jobs:
    hello-world-jobid:
        name: hello-job
        runs-on: ubuntu-latest
        steps:
            - name: hello-step
              run: |
               echo "hello-welcome to GHA"
               echo "this pipe symbol used for multiple shell commands"
              
                   
